server:
  port: 8080

spring:
  application:
    name: "gateway"
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user-services
          predicates:
            - Path=/profile/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:9001/eureka/"
